# Generated by Django 2.1.2 on 2018-12-22 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('img0', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('viewers', models.PositiveIntegerField(default=1)),
                ('extra_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('is_freezed', models.BooleanField(default=False)),
                ('contact', models.TextField(blank=True, null=True)),
                ('whatsApp', models.TextField(blank=True, null=True)),
                ('year_of_made', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)])),
                ('transmission', models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=120, null=True)),
                ('exterior_color', models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Blue', 'Blue'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Tan', 'Tan'), ('Brown', 'Brown'), ('Grey', 'Grey')], max_length=120, null=True)),
                ('interior_color', models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Blue', 'Blue'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Tan', 'Tan'), ('Brown', 'Brown'), ('Grey', 'Grey')], max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_is_hidden', models.BooleanField(default=False)),
                ('Kilometer', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Pickup Truck', 'Pickup Truck'), ('Sport', 'Sport'), ('MicroCar', 'MicroCar'), ('Van', 'Van')], max_length=120, null=True)),
                ('sunroof', models.CharField(blank=True, choices=[('No', 'No'), ('Normal', 'Normal'), ('Panorama', 'Panorama')], max_length=120, null=True)),
                ('convertable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=120)),
                ('is_special', models.CharField(max_length=4, null=True)),
                ('first_owner', models.CharField(blank=True, max_length=30, null=True)),
                ('is_from_kwait', models.CharField(blank=True, max_length=120, null=True)),
                ('is_under_warranty', models.CharField(blank=True, max_length=30, null=True)),
                ('is_get_accident', models.CharField(blank=True, max_length=30, null=True)),
                ('is_repainted', models.CharField(blank=True, max_length=120, null=True)),
                ('condition', models.CharField(blank=True, max_length=120, null=True)),
                ('is_accept_exam', models.CharField(max_length=120, null=True)),
                ('mini_price', models.IntegerField(blank=True, null=True)),
                ('has_visible_defect', models.CharField(blank=True, max_length=120, null=True)),
                ('comment', models.CharField(blank=True, max_length=120, null=True)),
                ('communication', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=120)),
                ('expo_token', models.TextField(blank=True, max_length=500, null=True)),
                ('phonenumber', models.CharField(max_length=120)),
                ('authy_id', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)])),
                ('year_to', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)])),
                ('price_start', models.IntegerField(blank=True, null=True)),
                ('price_end', models.IntegerField(blank=True, null=True)),
                ('trans_gear', models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=120, null=True)),
                ('kilo_from', models.IntegerField(blank=True, null=True)),
                ('kilo_to', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
