# Generated by Django 2.1.2 on 2018-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='authy_id',
            field=models.CharField(default='invalid', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default='invalid', max_length=120),
        ),
    ]
